version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pepo-postgres
    environment:
      POSTGRES_DB: pepo_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    networks:
      - pepo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pepo_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Uncomment this service when you want to run the app in Docker
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: pepo-app
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@postgres:5432/pepo_dev?sslmode=disable
  #     PORT: 8080
  #     ENV: development
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - pepo-network
  #   restart: unless-stopped
  #   volumes:
  #     - ./static:/app/static
  #     - ./templates:/app/templates

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pepo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pepo.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pepo-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  pepo-network:
    driver: bridge
