// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateAction implements createAction operation.
//
// Create a new action.
//
// POST /actions
func (UnimplementedHandler) CreateAction(ctx context.Context, req *CreateActionRequest) (r CreateActionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateConversation implements createConversation operation.
//
// Create a new conversation.
//
// POST /conversations
func (UnimplementedHandler) CreateConversation(ctx context.Context, req *CreateConversationRequest) (r CreateConversationRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreatePerson implements createPerson operation.
//
// Create a new person.
//
// POST /people
func (UnimplementedHandler) CreatePerson(ctx context.Context, req *CreatePersonRequest) (r CreatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteAction implements deleteAction operation.
//
// Delete an action.
//
// DELETE /actions/{id}
func (UnimplementedHandler) DeleteAction(ctx context.Context, params DeleteActionParams) (r DeleteActionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeletePerson implements deletePerson operation.
//
// Delete a person.
//
// DELETE /people/{id}
func (UnimplementedHandler) DeletePerson(ctx context.Context, params DeletePersonParams) (r DeletePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActionById implements getActionById operation.
//
// Get an action by ID.
//
// GET /actions/{id}
func (UnimplementedHandler) GetActionById(ctx context.Context, params GetActionByIdParams) (r GetActionByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetActions implements getActions operation.
//
// Get all actions.
//
// GET /actions
func (UnimplementedHandler) GetActions(ctx context.Context, params GetActionsParams) (r GetActionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPersonActions implements getPersonActions operation.
//
// Get actions for a specific person.
//
// GET /people/{id}/actions
func (UnimplementedHandler) GetPersonActions(ctx context.Context, params GetPersonActionsParams) (r GetPersonActionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPersonById implements getPersonById operation.
//
// Get a person by ID.
//
// GET /people/{id}
func (UnimplementedHandler) GetPersonById(ctx context.Context, params GetPersonByIdParams) (r GetPersonByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPersons implements getPersons operation.
//
// Get all persons.
//
// GET /people
func (UnimplementedHandler) GetPersons(ctx context.Context, params GetPersonsParams) (r GetPersonsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateAction implements updateAction operation.
//
// Update an action.
//
// PUT /actions/{id}
func (UnimplementedHandler) UpdateAction(ctx context.Context, req *UpdateActionRequest, params UpdateActionParams) (r UpdateActionRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdatePerson implements updatePerson operation.
//
// Update a person.
//
// PUT /people/{id}
func (UnimplementedHandler) UpdatePerson(ctx context.Context, req *UpdatePersonRequest, params UpdatePersonParams) (r UpdatePersonRes, _ error) {
	return r, ht.ErrNotImplemented
}
