package agent

import "encoding/json"

// Role represents the role of a chat message participant.
type Role string

const (
	// RoleSystem is used for system-level instructions.
	RoleSystem Role = "system"
	// RoleUser is used for user inputs.
	RoleUser Role = "user"
	// RoleAssistant is used for responses generated by the assistant model.
	RoleAssistant Role = "assistant"
	// RoleTool is used for outputs returned by tool calls.
	RoleTool Role = "tool"
)

// Message describes a single entry in the chat conversation between the user and the agent.
type Message struct {
	Role    Role   `json:"role"`
	Content string `json:"content"`
	// ToolCall is non-nil when the assistant wants to call a tool.
	ToolCall *ToolCall `json:"tool_call,omitempty"`
	// ToolCallID links tool responses back to the assistant's request for tracing.
	ToolCallID string `json:"tool_call_id,omitempty"`
	// Name is populated for tool response messages to indicate which tool produced the output.
	Name string `json:"name,omitempty"`
	// RawJSON can be used by LLM implementations that require the raw payload for rehydration.
	RawJSON json.RawMessage `json:"-"`
}

// ToolCall captures the request generated by the LLM to execute a specific tool.
type ToolCall struct {
	ID        string          `json:"id,omitempty"`
	Name      string          `json:"name"`
	Arguments json.RawMessage `json:"arguments"`
}
