// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LockWrapper() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"lock-overlay\" class=\"hidden fixed inset-0 bg-gray-900 bg-opacity-75 flex items-center justify-center z-50\"><div class=\"text-white text-2xl\">Press r to resume</div></div><script>\n                (function() {\n                        const overlay = document.getElementById('lock-overlay');\n                        let timer;\n                        function startTimer() {\n                                timer = setTimeout(() => {\n                                        overlay.classList.remove('hidden');\n                                }, 60000);\n                        }\n                        function resetTimer() {\n                                clearTimeout(timer);\n                                overlay.classList.add('hidden');\n                                startTimer();\n                        }\n                        ['mousemove','keydown','mousedown','touchstart'].forEach(event => {\n                                document.addEventListener(event, () => {\n                                        if (overlay.classList.contains('hidden')) {\n                                                resetTimer();\n                                        }\n                                });\n                        });\n                        document.addEventListener('keydown', (e) => {\n                                if (!overlay.classList.contains('hidden') && e.key === 'r') {\n                                        resetTimer();\n                                }\n                        });\n                        startTimer();\n                })();\n        </script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
