// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_themes.sql

package db

import (
	"context"
)

const addThemeToConversation = `-- name: AddThemeToConversation :exec
INSERT INTO conversation_theme (conversation_id, theme_id)
VALUES (x2b($1), x2b($2))
`

type AddThemeToConversationParams struct {
	ConversationID string `db:"conversation_id" json:"conversation_id"`
	ThemeID        string `db:"theme_id" json:"theme_id"`
}

func (q *Queries) AddThemeToConversation(ctx context.Context, arg AddThemeToConversationParams) error {
	_, err := q.db.ExecContext(ctx, addThemeToConversation, arg.ConversationID, arg.ThemeID)
	return err
}
