// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	AddThemeToAction(ctx context.Context, arg AddThemeToActionParams) error
	CountActions(ctx context.Context) (int64, error)
	CountActionsByPersonID(ctx context.Context, personID string) (int64, error)
	CountPersons(ctx context.Context) (int64, error)
	CreateAction(ctx context.Context, arg CreateActionParams) (CreateActionRow, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (CreatePersonRow, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (CreateThemeRow, error)
	DeleteAction(ctx context.Context, id string) error
	DeletePerson(ctx context.Context, id string) error
	DeleteTheme(ctx context.Context, id string) error
	GetActionByID(ctx context.Context, id string) (GetActionByIDRow, error)
	GetActionsByDateRange(ctx context.Context, arg GetActionsByDateRangeParams) ([]GetActionsByDateRangeRow, error)
	GetActionsWithPersonDetails(ctx context.Context, arg GetActionsWithPersonDetailsParams) ([]GetActionsWithPersonDetailsRow, error)
	GetPersonByID(ctx context.Context, id string) (GetPersonByIDRow, error)
	GetPersonByName(ctx context.Context, name string) (GetPersonByNameRow, error)
	GetRecentActionsByPersonID(ctx context.Context, arg GetRecentActionsByPersonIDParams) ([]GetRecentActionsByPersonIDRow, error)
	GetThemeByID(ctx context.Context, id string) (GetThemeByIDRow, error)
	ListActions(ctx context.Context, arg ListActionsParams) ([]ListActionsRow, error)
	ListActionsByPersonID(ctx context.Context, arg ListActionsByPersonIDParams) ([]ListActionsByPersonIDRow, error)
	ListActionsByPersonIDAndValence(ctx context.Context, arg ListActionsByPersonIDAndValenceParams) ([]ListActionsByPersonIDAndValenceRow, error)
	ListActionsByThemeID(ctx context.Context, arg ListActionsByThemeIDParams) ([]ListActionsByThemeIDRow, error)
	ListActionsByValence(ctx context.Context, arg ListActionsByValenceParams) ([]ListActionsByValenceRow, error)
	ListPersons(ctx context.Context, arg ListPersonsParams) ([]ListPersonsRow, error)
	ListPersonsWithLastAction(ctx context.Context, arg ListPersonsWithLastActionParams) ([]ListPersonsWithLastActionRow, error)
	ListThemes(ctx context.Context, arg ListThemesParams) ([]ListThemesRow, error)
	ListThemesByActionID(ctx context.Context, arg ListThemesByActionIDParams) ([]ListThemesByActionIDRow, error)
	ListThemesByPersonID(ctx context.Context, arg ListThemesByPersonIDParams) ([]ListThemesByPersonIDRow, error)
	RemoveThemeFromAction(ctx context.Context, arg RemoveThemeFromActionParams) error
	SearchActionsByDescription(ctx context.Context, arg SearchActionsByDescriptionParams) ([]SearchActionsByDescriptionRow, error)
	SearchPersonsByName(ctx context.Context, arg SearchPersonsByNameParams) ([]SearchPersonsByNameRow, error)
	UpdateAction(ctx context.Context, arg UpdateActionParams) (UpdateActionRow, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (UpdatePersonRow, error)
}

var _ Querier = (*Queries)(nil)
