openapi: 3.0.3
info:
  title: Performance Tracking API
  description: API for tracking performance of direct reports
  version: 1.0.0
  contact:
    name: Performance Tracking Team
    email: help@example.com

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /persons:
    get:
      summary: List all persons
      operationId: listPersons
      tags:
        - persons
      parameters:
        - name: limit
          in: query
          description: Maximum number of persons to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of persons to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: array
                    items:
                      $ref: "#/components/schemas/Person"
                  total:
                    type: integer
                    description: Total number of persons
                required:
                  - persons
                  - total
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a new person
      operationId: createPerson
      tags:
        - persons
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePersonRequest"
      responses:
        "201":
          description: Person created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /persons/{id}:
    get:
      summary: Get a person by ID
      operationId: getPerson
      tags:
        - persons
      parameters:
        - name: id
          in: path
          required: true
          description: Person ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        "404":
          description: Person not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Update a person
      operationId: updatePerson
      tags:
        - persons
      parameters:
        - name: id
          in: path
          required: true
          description: Person ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePersonRequest"
      responses:
        "200":
          description: Person updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Person not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Delete a person
      operationId: deletePerson
      tags:
        - persons
      parameters:
        - name: id
          in: path
          required: true
          description: Person ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      responses:
        "204":
          description: Person deleted successfully
        "404":
          description: Person not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /actions:
    get:
      summary: List all actions
      operationId: listActions
      tags:
        - actions
      parameters:
        - name: limit
          in: query
          description: Maximum number of actions to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of actions to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: person_id
          in: query
          description: Filter actions by person ID
          required: false
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
        - name: valence
          in: query
          description: Filter actions by valence
          required: false
          schema:
            type: string
            enum: [positive, negative]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Action"
                  total:
                    type: integer
                    description: Total number of actions
                required:
                  - actions
                  - total
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a new action
      operationId: createAction
      tags:
        - actions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateActionRequest"
      responses:
        "201":
          description: Action created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /actions/{id}:
    get:
      summary: Get an action by ID
      operationId: getAction
      tags:
        - actions
      parameters:
        - name: id
          in: path
          required: true
          description: Action ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
        "404":
          description: Action not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Update an action
      operationId: updateAction
      tags:
        - actions
      parameters:
        - name: id
          in: path
          required: true
          description: Action ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateActionRequest"
      responses:
        "200":
          description: Action updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Action"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Action not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Delete an action
      operationId: deleteAction
      tags:
        - actions
      parameters:
        - name: id
          in: path
          required: true
          description: Action ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
      responses:
        "204":
          description: Action deleted successfully
        "404":
          description: Action not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /persons/{id}/actions:
    get:
      summary: Get actions for a specific person
      operationId: getPersonActions
      tags:
        - actions
        - persons
      parameters:
        - name: id
          in: path
          required: true
          description: Person ID (xid)
          schema:
            type: string
            pattern: "^[0-9a-v]{20}$"
        - name: limit
          in: query
          description: Maximum number of actions to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of actions to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: valence
          in: query
          description: Filter actions by valence
          required: false
          schema:
            type: string
            enum: [positive, negative]
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  actions:
                    type: array
                    items:
                      $ref: "#/components/schemas/Action"
                  total:
                    type: integer
                    description: Total number of actions for this person
                required:
                  - actions
                  - total
        "404":
          description: Person not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier (xid)
          pattern: "^[0-9a-v]{20}$"
          example: "9m4e2mr0ui3e8a215n4g"
        name:
          type: string
          description: Person's full name
          minLength: 1
          maxLength: 255
          example: "John Doe"
        created_at:
          type: string
          format: date-time
          description: When the person was created
          example: "2023-12-01T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the person was last updated
          example: "2023-12-01T10:30:00Z"
      required:
        - id
        - name
        - created_at
        - updated_at

    CreatePersonRequest:
      type: object
      properties:
        name:
          type: string
          description: Person's full name
          minLength: 1
          maxLength: 255
          example: "John Doe"
      required:
        - name

    UpdatePersonRequest:
      type: object
      properties:
        name:
          type: string
          description: Person's full name
          minLength: 1
          maxLength: 255
          example: "John Doe"
      required:
        - name

    Action:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier (xid)
          pattern: "^[0-9a-v]{20}$"
          example: "9m4e2mr0ui3e8a215n4g"
        person_id:
          type: string
          description: ID of the person this action relates to
          pattern: "^[0-9a-v]{20}$"
          example: "9m4e2mr0ui3e8a215n4g"
        occurred_at:
          type: string
          format: date-time
          description: When the action occurred
          example: "2023-12-01T10:30:00Z"
        description:
          type: string
          description: Description of the action
          minLength: 1
          example: "Completed project ahead of schedule"
        references:
          type: string
          description: References or links related to the action
          nullable: true
          example: "https://github.com/user/repo/pull/123"
        valence:
          type: string
          description: Whether the action was positive or negative
          enum: [positive, negative]
          example: "positive"
        created_at:
          type: string
          format: date-time
          description: When the action record was created
          example: "2023-12-01T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: When the action record was last updated
          example: "2023-12-01T10:30:00Z"
      required:
        - id
        - person_id
        - occurred_at
        - description
        - valence
        - created_at
        - updated_at

    CreateActionRequest:
      type: object
      properties:
        person_id:
          type: string
          description: ID of the person this action relates to
          pattern: "^[0-9a-v]{20}$"
          example: "9m4e2mr0ui3e8a215n4g"
        occurred_at:
          type: string
          format: date-time
          description: When the action occurred (defaults to current time if not provided)
          example: "2023-12-01T10:30:00Z"
        description:
          type: string
          description: Description of the action
          minLength: 1
          example: "Completed project ahead of schedule"
        references:
          type: string
          description: References or links related to the action
          nullable: true
          example: "https://github.com/user/repo/pull/123"
        valence:
          type: string
          description: Whether the action was positive or negative
          enum: [positive, negative]
          example: "positive"
      required:
        - person_id
        - description
        - valence

    UpdateActionRequest:
      type: object
      properties:
        person_id:
          type: string
          description: ID of the person this action relates to
          pattern: "^[0-9a-v]{20}$"
          example: "9m4e2mr0ui3e8a215n4g"
        occurred_at:
          type: string
          format: date-time
          description: When the action occurred
          example: "2023-12-01T10:30:00Z"
        description:
          type: string
          description: Description of the action
          minLength: 1
          example: "Completed project ahead of schedule"
        references:
          type: string
          description: References or links related to the action
          nullable: true
          example: "https://github.com/user/repo/pull/123"
        valence:
          type: string
          description: Whether the action was positive or negative
          enum: [positive, negative]
          example: "positive"
      required:
        - person_id
        - occurred_at
        - description
        - valence

    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
          example: "Something went wrong"
        code:
          type: string
          description: Error code
          example: "INTERNAL_ERROR"
      required:
        - message
        - code

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
# Security disabled for development - uncomment when authentication is implemented
# security:
#   - bearerAuth: []
